package historia;

public class Historia {

	public static void main(String[] args) {
		System.out.println("El Tesoro de Umbra\r\n"
				+ "\r\n"
				+ "Escena 1: El Encuentro en la Loma\r\n"
				+ "\r\n"
				+ "Cira pastorea sus ovejas, mirando hacia el mar, soñando con una vida diferente.\r\n"
				+ "\r\n"
				+ "CIRA: (Suspira) Si tan solo pudiera escapar de esta rutina. ¡Anhelo la aventura!\r\n"
				+ "\r\n"
				+ "El nomada se acerca, su mirada penetrante.\r\n"
				+ "\r\n"
				+ "NOMADA: ¿Qué te preocupa, joven pastora? Tus ojos reflejan un anhelo profundo.\r\n"
				+ "\r\n"
				+ "CIRA: A veces siento que hay más allá de estas colinas. Algo que me llama.\r\n"
				+ "\r\n"
				+ "NOMADA: Y lo hay, Cira. Mucho más de lo que imaginas. (Le entrega la bolsa) Guarda esto. Podría serte útil en el futuro.\r\n"
				+ "\r\n"
				+ "CIRA: (Sorprendida) ¿Qué es esto?\r\n"
				+ "\r\n"
				+ "NOMADA: Un pequeño regalo. Un símbolo de tu búsqueda.\r\n"
				+ "\r\n"
				+ "Escena 2: La Codicia de Umbra\r\n"
				+ "\r\n"
				+ "Umbra, en su castillo, mira fijamente un mapa antiguo.\r\n"
				+ "\r\n"
				+ "UMBRA: (Con voz ronca) Ese tesoro debe ser mío. Me dará el poder y la riqueza que siempre he deseado.\r\n"
				+ "\r\n"
				+ "SILAS: Su Alteza, quizás deberíamos buscar otro camino. Los aldeanos empiezan a desconfiar.\r\n"
				+ "\r\n"
				+ "UMBRA: ¡Silencio, cobarde! Yo sé lo que hago.\r\n"
				+ "\r\n"
				+ "SILAS: Pero Cira y Emanuel... son fuertes y tienen muchos aliados.\r\n"
				+ "\r\n"
				+ "UMBRA: ¡No me importa! Los eliminaré si es necesario.\r\n"
				+ "\r\n"
				+ "Escena 3: La Cueva Secreta\r\n"
				+ "\r\n"
				+ "Cira, acompañada por Emanuel, entra en la cueva.\r\n"
				+ "\r\n"
				+ "CIRA: (Con voz temblorosa) ¿Qué secretos guarda este lugar?\r\n"
				+ "\r\n"
				+ "EMANUEL: No te preocupes, Cira. Estoy contigo.\r\n"
				+ "\r\n"
				+ "Encuentran el cofre.\r\n"
				+ "\r\n"
				+ "CIRA: ¡Es increíble! Pero... ¿qué haremos con él?\r\n"
				+ "\r\n"
				+ "EMANUEL: Podríamos compartirlo con el pueblo.\r\n"
				+ "\r\n"
				+ "CIRA: Sí, sería lo justo.\r\n"
				+ "\r\n"
				+ "Escena 4: La Confrontación\r\n"
				+ "\r\n"
				+ "Umbra y sus hombres rodean a Cira y Emanuel en la playa.\r\n"
				+ "\r\n"
				+ "UMBRA: ¡Entrégame el tesoro, Cira!\r\n"
				+ "\r\n"
				+ "CIRA: ¡Nunca! Este tesoro es para el pueblo.\r\n"
				+ "\r\n"
				+ "EMANUEL: ¡Defenderemos lo que es nuestro!\r\n"
				+ "\r\n"
				+ "UMBRA: ¡Sois unos insolentes! ¡Preparados para el ataque!\r\n"
				+ "\r\n"
				+ "SILAS: (En voz baja) Su Alteza, esto es una locura.\r\n"
				+ "\r\n"
				+ "Escena 5: La Decisión Final\r\n"
				+ "\r\n"
				+ "Después de una larga batalla, Umbra es derrotado.\r\n"
				+ "\r\n"
				+ "UMBRA: (Derrotado) ¡Maldición! ¡Nunca me vencerán!\r\n"
				+ "\r\n"
				+ "CIRA: (Mirando a Emanuel) Lo hemos logrado.\r\n"
				+ "\r\n"
				+ "EMANUEL: Gracias a ti, Cira. Y al nomada.\r\n"
				+ "\r\n"
				+ "NOMADA: El bien siempre triunfa sobre el mal.\r\n"
				+ "\r\n"
				+ "SILAS: (Arrepentido) Me arrepiento de haber servido a Umbra.\r\n"
				+ "\r\n"
				+ "Escena 6: El Nuevo Comienzo\r\n"
				+ "\r\n"
				+ "Cira y Emanuel se casan y comparten el tesoro con el pueblo.\r\n"
				+ "\r\n"
				+ "CIRA: (Brindando) Por un nuevo comienzo para Umbra.\r\n"
				+ "\r\n"
				+ "EMANUEL: Y por nuestro amor.\r\n"
				+ "\r\n"
				+ "NOMADA: (Sonriendo) La vida sigue su curso.\r\n"
				+ "\r\n"
				+ "SILAS: (Integraándose al pueblo) Prometo ser un hombre nuevo.\r\n"
				+ "\r\n"
				+ "UMBRA (voz en off): (Desde lejos) ¡Volveré!\r\n"
				+ "\r\n"
				+ "El pueblo celebra con alegría.\r\n"
				+ "\r\n"
				+ "CORO:\r\n"
				+ "\r\n"
				+ "En Umbra, donde el sol vuelve a brillar,\r\n"
				+ "La justicia y el amor siempre prevalecerán.");

	}

}
